# Generated by Django 3.2.25 on 2024-11-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0002_alter_gene_gene_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='access',
            field=models.IntegerField(default=0),
        ),
    ]
